debian/rules: work around flaky test t9128.3
t9128.3 is often causing git-svn to segfault and failing[1].

This appears to be a bug in libsvn, not git-svn.perl, so it should not
cause the git build to fail.  Omit the failing test from the main
"make test" run and run it separately while ignoring the result so we
can continue to gather data without making the git build unreliable.

[1]
Copying file:///«PKGBUILDDIR»/t/trash%20directory.t9128-git-svn-cmd-branch/svnrepo/trunk at r2 to file:///«PKGBUILDDIR»/t/trash%20directory.t9128-git-svn-cmd-branch/svnrepo/branches/a...
Found possible branch point: file:///«PKGBUILDDIR»/t/trash%20directory.t9128-git-svn-cmd-branch/svnrepo/trunk => file:///«PKGBUILDDIR»/t/trash%20directory.t9128-git-svn-cmd-branch/svnrepo/branches/a, 2
Found branch parent: (refs/remotes/origin/a) eed7341cd656e2fdb2fb9b36fbe4b039ba13e348
Following parent with do_switch
Successfully followed parent
r3 = 66a689f823e1002a376e324cce35d8c131f72bdc (refs/remotes/origin/a)
Copying file:///«PKGBUILDDIR»/t/trash%20directory.t9128-git-svn-cmd-branch/svnrepo/trunk at r2 to file:///«PKGBUILDDIR»/t/trash%20directory.t9128-git-svn-cmd-branch/svnrepo/branches/b...
Found possible branch point: file:///«PKGBUILDDIR»/t/trash%20directory.t9128-git-svn-cmd-branch/svnrepo/trunk => file:///«PKGBUILDDIR»/t/trash%20directory.t9128-git-svn-cmd-branch/svnrepo/branches/b, 2
Found branch parent: (refs/remotes/origin/b) eed7341cd656e2fdb2fb9b36fbe4b039ba13e348
Following parent with do_switch
Successfully followed parent
r4 = 3f86a479bd31164c206172f5ef7b1fcb7d43e4e1 (refs/remotes/origin/b)
error: git-svn died of signal 11

Signed-off-by: Jonathan Nieder <jrnieder@gmail.com>